version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: mesutal
      MYSQL_PASSWORD: Mesutal_1
    networks:
      - bookstorenet

  myapp:
    image: mesutal/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - bookstorenet

networks:
  bookstorenet:
    driver: bridge
